spring.application.name=gmg1

server.port=8888

logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.kr.ac.shingu.appfrm=DEBUG

#application-local.properties 을 읽기 위한 설정
spring.profiles.active=local